services:
  - type: web
    name: coqui-tts-api
    runtime: python-3.11.8
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
